/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 2f660cf967e0c1afaaa338e4b8a5fddd)
interface __BaseEnv_CloudflareEnv {
	ROUTING: KVNamespace;
	VIBRAIL_MANAGED_DOMAIN: "vibrail.app";
	VIBRAIL_ROUTE_CACHE_TTL: "30";
	VIBRAIL_ROUTE_NEGATIVE_CACHE_TTL: "2";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VIBRAIL_MANAGED_DOMAIN" | "VIBRAIL_ROUTE_CACHE_TTL" | "VIBRAIL_ROUTE_NEGATIVE_CACHE_TTL">> {}
}
