export type LandingLocale = "en" | "zh";
export type LandingTheme = "dark" | "light";

export const landingCopy = {
  en: {
    nav: {
      homeLabel: "Vibrail home",
      mainLabel: "Main navigation",
      platform: "Platform",
      workflow: "Workflow",
      operations: "Operations",
      collection: "Collection",
      docs: "Docs",
      about: "About",
      languageMenuLabel: "Select language",
      languageLabel: "Switch to Chinese",
      themeLightLabel: "Use light theme",
      themeDarkLabel: "Use dark theme",
    },
    hero: {
      eyebrow: "From prompt to production",
      title: "Ship software at the speed",
      accent: "your ideas arrive.",
      description: "Your vibe-coded app, live and secure. On Vibrail Cloud or any Linux VPS — zero infrastructure overhead.",
      primary: "Get started",
      secondary: "Docs",
      meta: ["Vibrail Cloud or your VPS", "Remote deploys over SSH", "Zero-downtime releases"],
    },
    prompt: {
      eyebrow: "Prompt-driven deploys",
      title: ["Describe it", "Vibrail ships it"],
      description: "Give the agent a repository and the result you want. It plans the infrastructure, builds the release, provisions dependencies, and returns a live service.",
      ariaLabel: "Mock prompt deployment interface",
      agentTitle: "Deployment Agent",
      mockPreview: "Mock preview",
      newDeployment: "New deployment",
      environments: "Environments",
      activity: "Activity",
      recent: "Recent",
      recentTasks: ["Deploy Northstar API", "Scale checkout worker", "Add a preview domain"],
      userPromptBefore: "Deploy ",
      userPromptAfter: " to a Singapore VPS. Add Postgres, expose the API publicly, and keep the database private.",
      agentName: "Vibrail Agent",
      completed: "Completed in 48 seconds",
      live: "Live",
      answer: "The application is running. I created an isolated network, attached Postgres, configured health checks, and routed the public domain to the API service.",
      progress: ["Inspect", "Plan", "Build", "Deploy"],
      productionRelease: "production · release v18",
      healthy: "Healthy",
      resultLabels: ["Target", "Repository", "Services", "Health"],
      resultDetails: ["Singapore", "main · a41c9de", "private network", "/health · 34ms"],
      composer: "Ask Vibrail to deploy, change, or inspect something…",
      sendLabel: "Send mock prompt",
      urlLabel: "Mock deployment URL",
    },
    cli: {
      eyebrow: "CLI deploys",
      title: ["One command", "Production ready"],
      description: "Prefer the terminal? The CLI uses the same build, release, routing, health-check, and rollback pipeline as the deployment agent.",
      ariaLabel: "Vibrail CLI deployment example",
      tabs: ["Deploy", "Observe", "Rollback"],
      live: "live",
      logs: ["Scanning project", "Building release", "Shipping artifact", "Warming containers", "Production is live"],
      healthy: "healthy",
      environment: "production",
      stats: ["status", "latency", "healthy", "release"],
      surfaces: "One control plane across",
      dashboard: "Dashboard",
    },
    metricsLabel: "Platform highlights",
    metrics: [
      ["Cloud", "managed deployment"],
      ["SSH", "VPS deployment"],
      ["1-click", "instant rollback"],
      ["Any VPS", "bring your own server"],
    ],
    platform: {
      eyebrow: "Core platform",
      title: ["From commit", "to production"],
      description: "A focused deployment layer that keeps the hard infrastructure work visible, repeatable and under your control.",
      features: [
        ["Deploy in one command", "Vibrail detects the stack, builds an immutable release, ships it over SSH, and brings it online with zero-downtime routing."],
        ["Your infrastructure, connected", "Run on Vibrail Cloud, any Linux server, or both. Move workloads without changing your application or giving up ownership."],
        ["Every release is reversible", "Versioned artifacts and retained releases make rollback a deliberate button press, not an incident response project."],
        ["Built for humans and agents", "Use the dashboard, CLI, or MCP. Every surface talks to the same deployment control plane."],
      ],
      productionLive: "production live",
    },
    workflow: {
      eyebrow: "How it works",
      title: ["Source to service", "One clear path"],
      description: "No builds running on production. No persistent Vibrail control-plane daemon on the target. Just immutable releases moving through a clear pipeline.",
      steps: [
        ["Connect", "Link a repository and choose Vibrail Cloud or a VPS. Vibrail detects the framework, package manager and runtime."],
        ["Build", "Create a versioned artifact away from production, with consistent configuration and repeatable output."],
        ["Ship & operate", "Stream the release over SSH, route traffic, watch health, and roll back from the same control plane."],
      ],
      infraEyebrow: "One topology, your choice of infrastructure",
      infraTitle: ["Cloud or VPS", "Same workflow"],
      infraDescription: "Choose managed Vibrail Cloud or connect a Linux VPS over SSH. The deployment workflow stays the same as your infrastructure grows.",
      explore: "Explore the architecture",
      controlPlane: "control plane",
      codingAgent: "Coding Agent",
      cloud: "Cloud",
      yourVps: "Your VPS",
    },
    operations: {
      eyebrow: "Operations included",
      title: ["Production essentials", "Built in"],
      description: "Vibrail keeps deployment, networking and day-two operations together so your team spends less time stitching tools together.",
      capabilities: [
        ["Domains & SSL", "Automatic certificates and traffic routing."],
        ["Managed services", "Postgres, Redis, mail, storage and more."],
        ["Secrets", "Encrypted, environment-scoped configuration."],
        ["Logs & metrics", "Live visibility across every service."],
        ["Preview releases", "A fresh URL for every branch and pull request."],
        ["Private by default", "Isolated networks with explicit exposure."],
      ],
    },
    cta: {
      eyebrow: "Ready when your code is.",
      title: "Ship the next version",
      dashboard: "Dashboard",
      secondary: "Docs",
    },
    footer: {
      homeLabel: "Vibrail home",
      description: "Deployment infrastructure that carries ideas from coding agents to reliable production services.",
      product: "Product",
      developers: "Developers",
      deploy: "Deploy",
      platform: "Platform",
      workflow: "Workflow",
      operations: "Operations",
      documentation: "Documentation",
      cliReference: "CLI reference",
      mcpServer: "MCP server",
      cloud: "Vibrail Cloud",
      connectVps: "Connect a VPS",
      quickstart: "Quickstart",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
    },
  },
  zh: {
    nav: {
      homeLabel: "Vibrail 首页",
      mainLabel: "主导航",
      platform: "平台",
      workflow: "工作流",
      operations: "运维",
      collection: "作品集",
      docs: "文档",
      about: "关于",
      languageMenuLabel: "选择语言",
      languageLabel: "切换到英文",
      themeLightLabel: "使用浅色主题",
      themeDarkLabel: "使用深色主题",
    },
    hero: {
      eyebrow: "从想法到生产环境",
      title: "软件交付",
      accent: "不再辜负灵感",
      description: "你的 vibe-coded 应用，即刻上线，安全无忧。部署到 Vibrail Cloud 或任意 Linux VPS - 零运维负担。",
      primary: "开始使用",
      secondary: "文档",
      meta: ["Vibrail Cloud 或你的 VPS", "通过 SSH 远程部署", "零停机发布"],
    },
    prompt: {
      eyebrow: "Prompt 驱动部署",
      title: ["描述结果", "Vibrail 来交付"],
      description: "告诉 agent 代码仓库和目标结果。它会规划基础设施、构建版本、配置依赖，并返回一个可访问的线上服务。",
      ariaLabel: "Prompt 部署模拟界面",
      agentTitle: "部署 Agent",
      mockPreview: "模拟预览",
      newDeployment: "新建部署",
      environments: "环境",
      activity: "活动",
      recent: "最近任务",
      recentTasks: ["部署 Northstar API", "扩容结算 Worker", "添加预览域名"],
      userPromptBefore: "将 ",
      userPromptAfter: " 部署到新加坡 VPS。添加 Postgres，对外开放 API，并保持数据库为私有服务。",
      agentName: "Vibrail Agent",
      completed: "48 秒内完成",
      live: "已上线",
      answer: "应用已经运行。我创建了隔离网络、连接 Postgres、配置健康检查，并将公共域名路由到 API 服务。",
      progress: ["检查", "规划", "构建", "部署"],
      productionRelease: "生产环境 · 版本 v18",
      healthy: "运行正常",
      resultLabels: ["目标", "代码仓库", "服务", "健康状态"],
      resultDetails: ["新加坡", "main · a41c9de", "私有网络", "/health · 34ms"],
      composer: "让 Vibrail 部署、修改或检查服务…",
      sendLabel: "发送模拟 Prompt",
      urlLabel: "模拟部署地址",
    },
    cli: {
      eyebrow: "CLI 部署",
      title: ["一条命令", "直达生产"],
      description: "习惯使用终端？CLI 与部署 agent 共享同一套构建、发布、路由、健康检查和回滚流程。",
      ariaLabel: "Vibrail CLI 部署示例",
      tabs: ["部署", "观测", "回滚"],
      live: "在线",
      logs: ["扫描项目", "构建版本", "传输制品", "启动容器", "生产环境已上线"],
      healthy: "健康",
      environment: "生产环境",
      stats: ["状态", "延迟", "健康实例", "版本"],
      surfaces: "统一控制平面支持",
      dashboard: "控制台",
    },
    metricsLabel: "平台能力概览",
    metrics: [
      ["Cloud", "托管部署"],
      ["SSH", "VPS 部署"],
      ["一键", "即时回滚"],
      ["任意 VPS", "使用你的服务器"],
    ],
    platform: {
      eyebrow: "核心平台",
      title: ["从代码提交", "到生产环境"],
      description: "专注的部署层，让复杂的基础设施工作清晰可见、可重复执行，并始终由你掌控。",
      features: [
        ["一条命令完成部署", "Vibrail 自动识别技术栈、构建不可变版本、通过 SSH 传输，并以零停机方式上线。"],
        ["连接你的基础设施", "运行在 Vibrail Cloud、任意 Linux VPS，或同时使用两者。迁移工作负载无需修改应用。"],
        ["每个版本都可回退", "版本化制品与历史发布记录，让回滚成为一次明确操作，而不是一场事故响应。"],
        ["为开发者与 Agent 构建", "通过控制台、CLI 或 MCP 操作，所有入口都连接到同一个部署控制平面。"],
      ],
      productionLive: "生产环境已上线",
    },
    workflow: {
      eyebrow: "工作方式",
      title: ["从源码", "到服务"],
      description: "生产服务器不执行构建，目标 VPS 不运行常驻的 Vibrail 控制平面进程，只有不可变版本沿着明确流程完成交付。",
      steps: [
        ["连接", "关联代码仓库并选择 Vibrail Cloud 或 VPS。Vibrail 会识别框架、包管理器和运行时。"],
        ["构建", "在生产环境之外生成版本化制品，确保配置一致、结果可重复。"],
        ["发布与运维", "通过 SSH 传输版本、路由流量、检查健康状态，并从同一控制平面执行回滚。"],
      ],
      infraEyebrow: "同一套拓扑，自由选择基础设施",
      infraTitle: ["Cloud 或 VPS", "流程不变"],
      infraDescription: "选择托管的 Vibrail Cloud，或通过 SSH 连接 Linux VPS。随着基础设施扩展，部署工作流始终保持一致。",
      explore: "查看架构",
      controlPlane: "控制平面",
      codingAgent: "Coding Agent",
      cloud: "Cloud",
      yourVps: "你的 VPS",
    },
    operations: {
      eyebrow: "内置运维能力",
      title: ["生产能力", "全部内置"],
      description: "Vibrail 将部署、网络和持续运维集中在一起，让团队无需再花时间拼接不同工具。",
      capabilities: [
        ["域名与 SSL", "自动签发证书并配置流量路由。"],
        ["托管服务", "Postgres、Redis、邮件、存储等服务。"],
        ["密钥管理", "加密并按环境隔离的配置。"],
        ["日志与指标", "实时查看每个服务的运行状态。"],
        ["预览版本", "为每个分支和合并请求生成独立地址。"],
        ["默认私有", "网络相互隔离，仅显式开放所需服务。"],
      ],
    },
    cta: {
      eyebrow: "代码准备好，Vibrail 就准备好。",
      title: "发布下一个版本",
      dashboard: "控制台",
      secondary: "文档",
    },
    footer: {
      homeLabel: "Vibrail 首页",
      description: "将 coding agent 产生的想法可靠地交付为生产服务的部署基础设施。",
      product: "产品",
      developers: "开发者",
      deploy: "部署",
      platform: "平台",
      workflow: "工作流",
      operations: "运维",
      documentation: "文档",
      cliReference: "CLI 参考",
      mcpServer: "MCP 服务",
      cloud: "Vibrail Cloud",
      connectVps: "连接 VPS",
      quickstart: "快速开始",
      privacy: "隐私政策",
      terms: "服务条款",
    },
  },
} as const;

export type LandingCopy = (typeof landingCopy)[LandingLocale];
